spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myssm?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useAffectedRows=true&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail:
    protocol: smtp
    host: smtp.126.com
    port: 25
    username: gyh_03@126.com
    password: gyh18600749749
  profiles:
    active: dev
    include: xxx-${spring.profiles.active:worry}
  messages: # 国际化配置
    encoding: UTF-8
    basename: i18n/message

server:
  port: 8088

#######################################
#指定mybatis-config.xml的位置
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*Mapper.xml





